import { memo } from 'react'
import { agentStatusLabel, type HerdrAgentInfo, type TmuxSession } from '../api'
import { Icon } from '../icons'

const statusClass = (agent: HerdrAgentInfo): string => ({ Working: 'working', Blocked: 'blocked', Idle: 'idle', Done: 'done', Unknown: 'unknown' }[agentStatusLabel(agent)])

type Props = { herdrVersion: string | null; herdrMissing: boolean; herdrError: string | null; agents: HerdrAgentInfo[]; bridgeInfo: { local: string; socket: string } | null; tmuxSessions: TmuxSession[]; newTmuxName: string; onNewTmuxName: (value: string) => void; onHerdrBridge: () => void; onHerdrBridgeStop: () => void; onHerdrAttach: () => void; onTmuxAttach: (name: string) => void; onTmuxKill: (name: string) => void; onTmuxCreate: () => void }

export const RuntimePanel = memo(function RuntimePanel({ herdrVersion, herdrMissing, herdrError, agents, bridgeInfo, tmuxSessions, newTmuxName, onNewTmuxName, onHerdrBridge, onHerdrBridgeStop, onHerdrAttach, onTmuxAttach, onTmuxKill, onTmuxCreate }: Props) {
  return <aside className="runtime-panel"><div className="runtime-block"><div className="runtime-title"><span>herdr</span><small title={herdrError ?? undefined}>{herdrMissing ? '未检测到' : (herdrVersion ?? (herdrError ? '暂不可用' : '检测中…'))}</small><button className="mini" onClick={onHerdrBridge} title="把远程 herdr socket 桥接到本地端口（需远程 socat）"><Icon name="link" size={10} />桥接</button><button className="mini" onClick={onHerdrAttach} title="在终端中启动 herdr TUI">启动</button></div>{bridgeInfo && <div className="bridge-note">{bridgeInfo.local} ↔ {bridgeInfo.socket}<button className="mini" onClick={onHerdrBridgeStop}>停止</button></div>}{agents.length === 0 ? <div className={`runtime-empty${herdrError ? ' error' : ''}`} title={herdrError ?? undefined}>{herdrMissing ? '远程未检测到 Herdr' : herdrError ? 'Herdr 已检测到，但 agent 列表暂不可用' : '没有运行中的 agent'}</div> : agents.map((agent, index) => <div className="agent-row" key={agent.name ?? agent.pane_id ?? String(index)}><span className={`agent-dot ${statusClass(agent)}`} /><span className="agent-name">{agent.name ?? '?'}</span><span className="agent-kind">{agent.kind ?? ''}</span><span className="agent-status">{agentStatusLabel(agent)}</span></div>)}</div><div className="runtime-block"><div className="runtime-title"><span>tmux</span><small>{tmuxSessions.length} 会话</small></div>{tmuxSessions.length === 0 && <div className="runtime-empty">暂无会话；可在下方新建</div>}{tmuxSessions.map((session) => <div className="tmux-row" key={session.name}><span className="tmux-name">{session.name}</span><span className="tmux-meta">{session.windows}w · {session.attached}a</span><button className="mini" onClick={() => onTmuxAttach(session.name)}>attach</button><button className="mini danger" onClick={() => { if (window.confirm(`确定删除 tmux 会话 ${session.name}？会话中的进程将终止。`)) onTmuxKill(session.name) }}>kill</button></div>)}<div className="tmux-create"><input value={newTmuxName} onChange={(event) => onNewTmuxName(event.target.value)} placeholder="新会话名" onKeyDown={(event) => { if (event.key === 'Enter') onTmuxCreate() }} /><button className="mini" onClick={onTmuxCreate}>新建</button></div></div></aside>
})
