import type { RefObject } from 'react'
import type { Host, TailscaleRuntimeInfo } from '../api'
import { Icon } from '../icons'

const firstAddress = (host: Host) => host.addresses.find((address) => address.enabled) ?? host.addresses[0]

type Props = {
  draft: Host
  tailscaleComponents: TailscaleRuntimeInfo | null
  tailscaleKeyInputRef: RefObject<HTMLInputElement | null>
  privateKeyPassphraseRef: RefObject<HTMLInputElement | null>
  updateDraft: (update: (host: Host) => Host) => void
  onClose: () => void
  onSave: () => void
  onMessage: (message: string) => void
}

export function HostEditor({ draft, tailscaleComponents, tailscaleKeyInputRef, privateKeyPassphraseRef, updateDraft, onClose, onSave, onMessage }: Props) {
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="host-modal host-editor" onSubmit={(event) => { event.preventDefault(); onSave() }}><div className="modal-head"><div><div className="eyebrow">HOST CONFIGURATION</div><h2>编辑工作站</h2></div><button type="button" className="ghost" onClick={onClose}>关闭</button></div>
    <section className="config-section"><div className="config-section-title">连接</div><div className="modal-grid two-columns"><label className="wide">名称<input value={draft.label} onChange={(event) => updateDraft((host) => ({ ...host, label: event.target.value }))} autoFocus /></label><label className="wide">地址<input value={firstAddress(draft)?.hostname_or_ip ?? ''} onChange={(event) => updateDraft((host) => ({ ...host, addresses: host.addresses.map((address, index) => index === 0 ? { ...address, hostname_or_ip: event.target.value } : address) }))} placeholder="100.x.x.x、MagicDNS 名称或公网地址" /></label><label>端口<input type="number" min="1" max="65535" value={draft.port} onChange={(event) => updateDraft((host) => ({ ...host, port: Number(event.target.value), addresses: host.addresses.map((address, index) => index === 0 ? { ...address, port: Number(event.target.value) } : address) }))} /></label><label>用户名<input value={draft.username} onChange={(event) => updateDraft((host) => ({ ...host, username: event.target.value }))} /></label><label>运行时<select value={draft.default_runtime} onChange={(event) => updateDraft((host) => ({ ...host, default_runtime: event.target.value as Host['default_runtime'] }))}><option value="Tmux">tmux</option><option value="Herdr">herdr</option><option value="PlainShell">普通 Shell</option></select></label><label>地址类型<select value={firstAddress(draft)?.kind ?? 'Manual'} onChange={(event) => updateDraft((host) => ({ ...host, addresses: host.addresses.map((address, index) => index === 0 ? { ...address, kind: event.target.value as Host['addresses'][number]['kind'] } : address) }))}><option value="Tailscale">Tailscale</option><option value="Lan">LAN</option><option value="Public">公网</option><option value="JumpHost">跳板机</option><option value="Manual">手动</option></select></label><label className="wide">固定文件目录 <span className="label-hint">打开文件页时自动进入</span><input value={draft.default_remote_path} onChange={(event) => updateDraft((host) => ({ ...host, default_remote_path: event.target.value || '/' }))} placeholder="例如 /home/user/project" spellCheck={false} /></label></div></section>
    <section className="config-section"><div className="config-section-title">SSH 认证</div><div className="modal-grid two-columns"><label className="wide">认证方式<select value={draft.auth_mode} onChange={(event) => updateDraft((host) => ({ ...host, auth_mode: event.target.value as Host['auth_mode'], private_key_path: event.target.value === 'PublicKey' ? host.private_key_path : null }))}><option value="Password">密码</option><option value="PublicKey">自定义私钥</option><option value="SshAgent">SSH Agent / Pageant</option><option value="KeyboardInteractive">Keyboard-interactive / MFA</option></select></label>{draft.auth_mode === 'PublicKey' && <><label className="wide">私钥文件<span className="input-with-button"><input value={draft.private_key_path ?? ''} onChange={(event) => updateDraft((host) => ({ ...host, private_key_path: event.target.value || null }))} placeholder="~/.ssh/id_ed25519" spellCheck={false} /><button type="button" className="mini" onClick={() => { void import('@tauri-apps/plugin-dialog').then(({ open }) => open({ multiple: false, directory: false })).then((path) => { if (typeof path === 'string') updateDraft((host) => ({ ...host, private_key_path: path })) }).catch((error) => onMessage('选择私钥失败：' + String(error))) }}>浏览…</button></span></label><label className="wide">私钥口令 <span className="label-hint">可选，留空保持现有口令</span><input ref={privateKeyPassphraseRef} type="password" autoComplete="off" spellCheck={false} placeholder={draft.auth_ref ? '已安全保存；留空保持不变' : '仅加密私钥需要'} /></label></>}{draft.auth_mode === 'SshAgent' && <p className="modal-note wide">优先连接系统 SSH Agent，失败后自动尝试 Pageant（若可用）；私钥不会离开 Agent。</p>}{draft.auth_mode === 'KeyboardInteractive' && <p className="modal-note wide">连接时按服务器提示显示密码、一次性验证码或多因素认证问题；响应只用于当前认证轮次。</p>}</div></section>
    <section className="config-section"><div className="config-section-title">跳板机 <span>可选</span></div><div className="modal-grid jump-grid"><label>主机<input value={draft.jump?.hostname ?? ''} onChange={(event) => updateDraft((host) => ({ ...host, jump: { hostname: event.target.value, port: host.jump?.port ?? 22, username: host.jump?.username ?? host.username } }))} placeholder="bastion.example.com" /></label><label>端口<input type="number" min="1" max="65535" value={draft.jump?.port ?? 22} onChange={(event) => updateDraft((host) => ({ ...host, jump: { hostname: host.jump?.hostname ?? '', port: Number(event.target.value), username: host.jump?.username ?? host.username } }))} /></label><label>用户名<input value={draft.jump?.username ?? ''} onChange={(event) => updateDraft((host) => ({ ...host, jump: { hostname: host.jump?.hostname ?? '', port: host.jump?.port ?? 22, username: event.target.value } }))} placeholder="与目标相同可留空" /></label></div></section>
    <section className="config-section tailscale-section"><label className="toggle-row"><input type="checkbox" checked={draft.tailscale?.enabled ?? false} onChange={(event) => updateDraft((host) => { const current = host.tailscale ?? { enabled: false, mode: 'Disabled' as const, device_name: null, auth_key_ref: null, state_dir: null }; return { ...host, tailscale: { ...current, enabled: event.target.checked, mode: event.target.checked && current.mode === 'Disabled' ? 'EmbeddedUserspace' : (event.target.checked ? current.mode : 'Disabled') } } })} /><span><strong>启用 Tailscale</strong><small>自动发现 tailnet 地址并参与连接回退</small></span></label>{draft.tailscale?.enabled && <div className="modal-grid two-columns tailscale-fields"><label className="wide">运行模式<select value={draft.tailscale.mode} onChange={(event) => updateDraft((host) => host.tailscale ? { ...host, tailscale: { ...host.tailscale, mode: event.target.value as NonNullable<Host['tailscale']>['mode'] } } : host)}><option value="SystemDaemon">系统服务（只读发现，不修改系统登录）</option><option value="EmbeddedUserspace">内置用户态（Kodework 私有状态）</option></select></label><div className={`tailscale-component-status wide ${tailscaleComponents?.cli_available && tailscaleComponents.daemon_available ? 'ok' : 'error'}`}><Icon name={tailscaleComponents?.cli_available && tailscaleComponents.daemon_available ? 'check' : 'warning'} size={13} />{tailscaleComponents ? (tailscaleComponents.cli_available && tailscaleComponents.daemon_available ? `内置 Tailscale ${tailscaleComponents.bundled_version} 组件完整，可直接使用` : '内置 Tailscale 组件缺失，请重新安装完整安装包') : '正在检查内置 Tailscale 组件…'}</div><label className="wide">设备名 <span className="label-hint">可选</span><input value={draft.tailscale.device_name ?? ''} onChange={(event) => updateDraft((host) => host.tailscale ? { ...host, tailscale: { ...host.tailscale, device_name: event.target.value || null } } : host)} placeholder="例如 kodework-windows" /></label>{draft.tailscale.mode === 'EmbeddedUserspace' && <label className="wide">私有状态文件 <span className="label-hint">留空自动管理</span><input value={draft.tailscale.state_dir ?? ''} onChange={(event) => updateDraft((host) => host.tailscale ? { ...host, tailscale: { ...host.tailscale, state_dir: event.target.value || null } } : host)} placeholder="例如 D:\\Kodework\\tailscale.state" /></label>}{draft.tailscale.mode === 'EmbeddedUserspace' && <label className="wide">Auth Key<input ref={tailscaleKeyInputRef} type="password" autoComplete="off" spellCheck={false} placeholder={draft.tailscale.auth_key_ref ? '已安全保存；留空保持不变' : '仅首次注册需要，保存后不回显'} /></label>}</div>}</section>
    <div className="security-note"><Icon name="check" size={13} />密码与私钥口令由当前操作系统的安全密钥环管理；私钥本体保留在你选择的文件中，SQLite 只保存路径和引用。</div><div className="modal-actions sticky-actions"><button className="ghost" type="button" onClick={onClose}>取消</button><button className="primary" type="submit"><Icon name="check" size={13} />保存工作站</button></div>
  </form></div>
}
