import type { RefObject } from 'react'
import type { Host, TailscaleRuntimeInfo } from '../api'
import type { Language } from '../i18n'
import { Icon } from '../icons'

const firstAddress = (host: Host) => host.addresses.find((address) => address.enabled) ?? host.addresses[0]

type Props = {
  draft: Host
  language: Language
  tailscaleComponents: TailscaleRuntimeInfo | null
  tailscaleKeyInputRef: RefObject<HTMLInputElement | null>
  privateKeyPassphraseRef: RefObject<HTMLInputElement | null>
  updateDraft: (update: (host: Host) => Host) => void
  onClose: () => void
  onSave: () => void
  onMessage: (message: string) => void
}

type EditorLabels = {
  eyebrow: string; title: string; close: string; connection: string; name: string; address: string; addressPlaceholder: string; port: string; username: string; runtime: string; plainShell: string; addressKind: string; publicAddress: string; jumpHost: string; manual: string; fixedFolder: string; fixedFolderHint: string; fixedFolderPlaceholder: string; authentication: string; authMode: string; password: string; privateKey: string; sshAgent: string; keyboardInteractive: string; privateKeyFile: string; browse: string; privateKeyPassphrase: string; savedKeep: string; encryptedOnly: string; agentNote: string; keyboardNote: string; bastion: string; optional: string; bastionHost: string; bastionPort: string; bastionUser: string; bastionUserPlaceholder: string; tailscale: string; tailscaleHint: string; mode: string; systemDaemon: string; embeddedUserspace: string; deviceName: string; deviceOptional: string; devicePlaceholder: string; stateDir: string; stateDirHint: string; stateDirPlaceholder: string; authKey: string; authKeySaved: string; authKeyFirstUse: string; componentChecking: string; componentReady: (version: string) => string; componentMissing: string; security: string; cancel: string; save: string; selectKeyFailed: (error: string) => string
}

function labelsFor(language: Language): EditorLabels {
  if (language === 'en-US') return {
    eyebrow: 'WORKSTATION CONFIGURATION', title: 'Edit workstation', close: 'Close', connection: 'Connection', name: 'Name', address: 'Address', addressPlaceholder: '100.x.x.x, MagicDNS name, or public address', port: 'Port', username: 'Username', runtime: 'Runtime', plainShell: 'Plain shell', addressKind: 'Address type', publicAddress: 'Public', jumpHost: 'Jump host', manual: 'Manual', fixedFolder: 'Pinned remote folder', fixedFolderHint: 'Opened automatically in Files', fixedFolderPlaceholder: 'For example /home/user/project', authentication: 'SSH authentication', authMode: 'Authentication method', password: 'Password', privateKey: 'Custom private key', sshAgent: 'SSH Agent / Pageant', keyboardInteractive: 'Keyboard-interactive / MFA', privateKeyFile: 'Private key file', browse: 'Browse…', privateKeyPassphrase: 'Private-key passphrase', savedKeep: 'saved securely; leave blank to keep it', encryptedOnly: 'only needed for encrypted keys', agentNote: 'The system SSH Agent is tried first, then Pageant when available. Private-key material stays inside the agent.', keyboardNote: 'Server prompts for a password, one-time code, or MFA response appear during connection. Responses are used only for this authentication round.', bastion: 'Jump host', optional: 'optional', bastionHost: 'Host', bastionPort: 'Port', bastionUser: 'Username', bastionUserPlaceholder: 'Leave blank to use the target username', tailscale: 'Enable Tailscale', tailscaleHint: 'Discover tailnet addresses and include them in connection fallback', mode: 'Mode', systemDaemon: 'System daemon (read-only discovery; does not change system login)', embeddedUserspace: 'Embedded userspace (private KodeWork state)', deviceName: 'Device name', deviceOptional: 'optional', devicePlaceholder: 'For example kodework-windows', stateDir: 'Private state file', stateDirHint: 'leave blank for automatic management', stateDirPlaceholder: 'For example D:\\Kodework\\tailscale.state', authKey: 'Auth key', authKeySaved: 'saved securely; leave blank to keep it', authKeyFirstUse: 'needed only for first registration; never shown again', componentChecking: 'Checking bundled Tailscale components…', componentReady: (version) => 'Bundled Tailscale ' + version + ' is ready', componentMissing: 'Bundled Tailscale components are incomplete; reinstall the full package', security: 'Passwords and key passphrases are kept in the operating system secret store. The private-key file stays at the path you choose; SQLite stores only references and non-secret metadata.', cancel: 'Cancel', save: 'Save workstation', selectKeyFailed: (error) => 'Could not choose private key: ' + error
  }
  return { eyebrow: '工作站配置', title: '编辑工作站', close: '关闭', connection: '连接', name: '名称', address: '地址', addressPlaceholder: '100.x.x.x、MagicDNS 名称或公网地址', port: '端口', username: '用户名', runtime: '运行时', plainShell: '普通 Shell', addressKind: '地址类型', publicAddress: '公网', jumpHost: '跳板机', manual: '手动', fixedFolder: '固定文件目录', fixedFolderHint: '打开文件页时自动进入', fixedFolderPlaceholder: '例如 /home/user/project', authentication: 'SSH 认证', authMode: '认证方式', password: '密码', privateKey: '自定义私钥', sshAgent: 'SSH Agent / Pageant', keyboardInteractive: 'Keyboard-interactive / MFA', privateKeyFile: '私钥文件', browse: '浏览…', privateKeyPassphrase: '私钥口令', savedKeep: '已安全保存；留空保持不变', encryptedOnly: '仅加密私钥需要', agentNote: '优先连接系统 SSH Agent，失败后自动尝试 Pageant（若可用）；私钥不会离开 Agent。', keyboardNote: '连接时按服务器提示显示密码、一次性验证码或多因素认证问题；响应只用于当前认证轮次。', bastion: '跳板机', optional: '可选', bastionHost: '主机', bastionPort: '端口', bastionUser: '用户名', bastionUserPlaceholder: '与目标相同可留空', tailscale: '启用 Tailscale', tailscaleHint: '自动发现 tailnet 地址并参与连接回退', mode: '运行模式', systemDaemon: '系统服务（只读发现，不修改系统登录）', embeddedUserspace: '内置用户态（KodeWork 私有状态）', deviceName: '设备名', deviceOptional: '可选', devicePlaceholder: '例如 kodework-windows', stateDir: '私有状态文件', stateDirHint: '留空自动管理', stateDirPlaceholder: '例如 D:\\Kodework\\tailscale.state', authKey: 'Auth Key', authKeySaved: '已安全保存；留空保持不变', authKeyFirstUse: '仅首次注册需要，保存后不回显', componentChecking: '正在检查内置 Tailscale 组件…', componentReady: (version) => '内置 Tailscale ' + version + ' 组件完整，可直接使用', componentMissing: '内置 Tailscale 组件缺失，请重新安装完整安装包', security: '密码与私钥口令由当前操作系统的安全密钥环管理；私钥本体保留在你选择的文件中，SQLite 只保存路径和引用。', cancel: '取消', save: '保存工作站', selectKeyFailed: (error) => '选择私钥失败：' + error }
}

export function HostEditor({ draft, language, tailscaleComponents, tailscaleKeyInputRef, privateKeyPassphraseRef, updateDraft, onClose, onSave, onMessage }: Props) {
  const labels = labelsFor(language)
  const address = firstAddress(draft)
  const selectedAddressId = address?.id
  const updateSelectedAddress = (host: Host, update: (address: Host['addresses'][number]) => Host['addresses'][number]): Host => ({
    ...host,
    addresses: selectedAddressId
      ? host.addresses.map((item) => item.id === selectedAddressId ? update(item) : item)
      : host.addresses,
  })
  const tailscaleReady = Boolean(tailscaleComponents?.cli_available && tailscaleComponents.daemon_available)
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="host-modal host-editor" onSubmit={(event) => { event.preventDefault(); onSave() }}><div className="modal-head"><div><div className="eyebrow">{labels.eyebrow}</div><h2>{labels.title}</h2></div><button type="button" className="ghost" onClick={onClose}>{labels.close}</button></div>
    <section className="config-section"><div className="config-section-title">{labels.connection}</div><div className="modal-grid two-columns"><label className="wide">{labels.name}<input value={draft.label} onChange={(event) => updateDraft((host) => ({ ...host, label: event.target.value }))} autoFocus /></label><label className="wide">{labels.address}<input value={address?.hostname_or_ip ?? ''} onChange={(event) => updateDraft((host) => updateSelectedAddress(host, (item) => ({ ...item, hostname_or_ip: event.target.value })))} placeholder={labels.addressPlaceholder} /></label><label>{labels.port}<input type="number" min="1" max="65535" value={draft.port} onChange={(event) => updateDraft((host) => updateSelectedAddress({ ...host, port: Number(event.target.value) }, (item) => ({ ...item, port: Number(event.target.value) })))} /></label><label>{labels.username}<input value={draft.username} onChange={(event) => updateDraft((host) => ({ ...host, username: event.target.value }))} /></label><label>{labels.runtime}<select value={draft.default_runtime} onChange={(event) => updateDraft((host) => ({ ...host, default_runtime: event.target.value as Host['default_runtime'] }))}><option value="Tmux">tmux</option><option value="Herdr">herdr</option><option value="PlainShell">{labels.plainShell}</option></select></label><label>{labels.addressKind}<select value={address?.kind ?? 'Manual'} onChange={(event) => updateDraft((host) => updateSelectedAddress(host, (item) => ({ ...item, kind: event.target.value as Host['addresses'][number]['kind'] })))}><option value="Tailscale">Tailscale</option><option value="Lan">LAN</option><option value="Public">{labels.publicAddress}</option><option value="JumpHost">{labels.jumpHost}</option><option value="Manual">{labels.manual}</option></select></label><label className="wide">{labels.fixedFolder} <span className="label-hint">{labels.fixedFolderHint}</span><input value={draft.default_remote_path} onChange={(event) => updateDraft((host) => ({ ...host, default_remote_path: event.target.value || '/' }))} placeholder={labels.fixedFolderPlaceholder} spellCheck={false} /></label></div></section>
    <section className="config-section"><div className="config-section-title">{labels.authentication}</div><div className="modal-grid two-columns"><label className="wide">{labels.authMode}<select value={draft.auth_mode} onChange={(event) => updateDraft((host) => ({ ...host, auth_mode: event.target.value as Host['auth_mode'], private_key_path: event.target.value === 'PublicKey' ? host.private_key_path : null }))}><option value="Password">{labels.password}</option><option value="PublicKey">{labels.privateKey}</option><option value="SshAgent">{labels.sshAgent}</option><option value="KeyboardInteractive">{labels.keyboardInteractive}</option></select></label>{draft.auth_mode === 'PublicKey' && <><label className="wide">{labels.privateKeyFile}<span className="input-with-button"><input value={draft.private_key_path ?? ''} onChange={(event) => updateDraft((host) => ({ ...host, private_key_path: event.target.value || null }))} placeholder="~/.ssh/id_ed25519" spellCheck={false} /><button type="button" className="mini" onClick={() => { void import('@tauri-apps/plugin-dialog').then(({ open }) => open({ multiple: false, directory: false })).then((path) => { if (typeof path === 'string') updateDraft((host) => ({ ...host, private_key_path: path })) }).catch((error) => onMessage(labels.selectKeyFailed(String(error)))) }}>{labels.browse}</button></span></label><label className="wide">{labels.privateKeyPassphrase} <span className="label-hint">{draft.auth_ref ? labels.savedKeep : labels.encryptedOnly}</span><input ref={privateKeyPassphraseRef} type="password" autoComplete="off" spellCheck={false} placeholder={draft.auth_ref ? labels.savedKeep : labels.encryptedOnly} /></label></>}{draft.auth_mode === 'SshAgent' && <p className="modal-note wide">{labels.agentNote}</p>}{draft.auth_mode === 'KeyboardInteractive' && <p className="modal-note wide">{labels.keyboardNote}</p>}</div></section>
    <section className="config-section"><div className="config-section-title">{labels.bastion} <span>{labels.optional}</span></div><div className="modal-grid jump-grid"><label>{labels.bastionHost}<input value={draft.jump?.hostname ?? ''} onChange={(event) => updateDraft((host) => ({ ...host, jump: { hostname: event.target.value, port: host.jump?.port ?? 22, username: host.jump?.username ?? host.username } }))} placeholder="bastion.example.com" /></label><label>{labels.bastionPort}<input type="number" min="1" max="65535" value={draft.jump?.port ?? 22} onChange={(event) => updateDraft((host) => ({ ...host, jump: { hostname: host.jump?.hostname ?? '', port: Number(event.target.value), username: host.jump?.username ?? host.username } }))} /></label><label>{labels.bastionUser}<input value={draft.jump?.username ?? ''} onChange={(event) => updateDraft((host) => ({ ...host, jump: { hostname: host.jump?.hostname ?? '', port: host.jump?.port ?? 22, username: event.target.value } }))} placeholder={labels.bastionUserPlaceholder} /></label></div></section>
    <section className="config-section tailscale-section"><label className="toggle-row"><input type="checkbox" checked={draft.tailscale?.enabled ?? false} onChange={(event) => updateDraft((host) => { const current = host.tailscale ?? { enabled: false, mode: 'Disabled' as const, device_name: null, auth_key_ref: null, state_dir: null }; return { ...host, tailscale: { ...current, enabled: event.target.checked, mode: event.target.checked && current.mode === 'Disabled' ? 'EmbeddedUserspace' : (event.target.checked ? current.mode : 'Disabled') } } })} /><span><strong>{labels.tailscale}</strong><small>{labels.tailscaleHint}</small></span></label>{draft.tailscale?.enabled && <div className="modal-grid two-columns tailscale-fields"><label className="wide">{labels.mode}<select value={draft.tailscale.mode} onChange={(event) => updateDraft((host) => host.tailscale ? { ...host, tailscale: { ...host.tailscale, mode: event.target.value as NonNullable<Host['tailscale']>['mode'] } } : host)}><option value="SystemDaemon">{labels.systemDaemon}</option><option value="EmbeddedUserspace">{labels.embeddedUserspace}</option></select></label><div className={'tailscale-component-status wide ' + (tailscaleReady ? 'ok' : 'error')}><Icon name={tailscaleReady ? 'check' : 'warning'} size={13} />{tailscaleComponents ? (tailscaleReady ? labels.componentReady(tailscaleComponents.bundled_version) : labels.componentMissing) : labels.componentChecking}</div><label className="wide">{labels.deviceName} <span className="label-hint">{labels.deviceOptional}</span><input value={draft.tailscale.device_name ?? ''} onChange={(event) => updateDraft((host) => host.tailscale ? { ...host, tailscale: { ...host.tailscale, device_name: event.target.value || null } } : host)} placeholder={labels.devicePlaceholder} /></label>{draft.tailscale.mode === 'EmbeddedUserspace' && <label className="wide">{labels.stateDir} <span className="label-hint">{labels.stateDirHint}</span><input value={draft.tailscale.state_dir ?? ''} onChange={(event) => updateDraft((host) => host.tailscale ? { ...host, tailscale: { ...host.tailscale, state_dir: event.target.value || null } } : host)} placeholder={labels.stateDirPlaceholder} spellCheck={false} /></label>}{draft.tailscale.mode === 'EmbeddedUserspace' && <label className="wide">{labels.authKey}<input ref={tailscaleKeyInputRef} type="password" autoComplete="off" spellCheck={false} placeholder={draft.tailscale.auth_key_ref ? labels.authKeySaved : labels.authKeyFirstUse} /></label>}</div>}</section>
    <div className="security-note"><Icon name="check" size={13} />{labels.security}</div><div className="modal-actions sticky-actions"><button className="ghost" type="button" onClick={onClose}>{labels.cancel}</button><button className="primary" type="submit"><Icon name="check" size={13} />{labels.save}</button></div>
  </form></div>
}
